name: Issue Form to profile.json
on:
  issues:
    types: [opened, edited, labeled]
permissions:
  contents: write
  issues: read
jobs:
  update-json:
    if: contains(github.event.issue.labels.*.name, 'cv-update')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract Issue Form fields
        id: parse
        uses: peter-murray/issue-forms-body-parser@v4.0.0
        with:
          issue-body: ${{ github.event.issue.body }}

      - name: Build profile.json
        run: |
          node -e "
            const fs=require('fs');
            const inpt = JSON.parse(process.env.FIELDS);
            const lines = s => (s||'').split('\n').map(x=>x.trim()).filter(Boolean);
            const tryJson = s => { try { return JSON.parse(s||'[]'); } catch { return []; } };

            const data = {
              name: inpt.name || '',
              headline: inpt.headline || '',
              avatar: inpt.avatar || '',
              email: inpt.email || '',
              phone: inpt.phone || '',
              location: inpt.location || '',
              links: tryJson(inpt.links),
              core_competencies: lines(inpt.core_competencies),
              technical_skills: lines(inpt.technical_skills),
              languages: tryJson(inpt.languages),
              experience: tryJson(inpt.experience),
              education: tryJson(inpt.education),
              projects: tryJson(inpt.projects)
            };
            fs.writeFileSync('profile.json', JSON.stringify(data, null, 2));
          "
        env:
          FIELDS: ${{ steps.parse.outputs.payload }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile.json
          git commit -m "Update profile.json from issue #${{ github.event.issue.number }}" || echo "No changes"
          git push

      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✅ Updated **profile.json**. Your CV site will reflect the changes shortly."
            })
